-----------------------------------------------------------------------------------------------------------------------------------------
-- NOFULL
-----------------------------------------------------------------------------------------------------------------------------------------
noFull = {
	["chip"] = true,
	["ametista"] = true,
	["esmeralda"] = true,
	["rubi"] = true,
	["safira"] = true,
	["premiumplate"] = true,
	["newgarage"] = true,
	["newchars"] = true,
	["newprops"] = true,
	["homecont01"] = true,
	["homecont02"] = true,
	["homecont03"] = true,
	["homecont04"] = true,
	["homecont05"] = true,
	["homecont06"] = true,
	["homecont07"] = true,
	["homecont08"] = true,
	["homecont09"] = true,
	["homecont09"] = true
}

-----------------------------------------------------------------------------------------------------------------------------------------
-- NOSTORE
-----------------------------------------------------------------------------------------------------------------------------------------
noStore = {
	["octopus"] = true,
	["shrimp"] = true,
	["carp"] = true,
	["codfish"] = true,
	["catfish"] = true,
	["goldenfish"] = true,
	["horsefish"] = true,
	["tilapia"] = true,
	["pacu"] = true,
	["pirarucu"] = true,
	["tambaqui"] = true,
	["meatA"] = true,
	["meatB"] = true,
	["meatC"] = true,
	["meatS"] = true,
	["energetic"] = true,
	["water"] = true,
	["dirtywater"] = true,
	["coffee"] = true,
	["cola"] = true,
	["tacos"] = true,
	["fries"] = true,
	["soda"] = true,
	["hamburger"] = true,
	["hamburger2"] = true,
	["hamburger3"] = true,
	["hamburger4"] = true,
	["hamburger5"] = true,
	["hotdog"] = true,
	["donut"] = true,
	["chocolate"] = true,
	["sandwich"] = true,
	["absolut"] = true,
	["chandon"] = true,
	["dewars"] = true,
	["hennessy"] = true,
	["ketchup"] = true,
	["orange"] = true,
	["strawberry"] = true,
	["grape"] = true,
	["tange"] = true,
	["banana"] = true,
	["passion"] = true,
	["tomato"] = true,
	["orangejuice"] = true,
	["tangejuice"] = true,
	["grapejuice"] = true,
	["strawberryjuice"] = true,
	["bananajuice"] = true,
	["passionjuice"] = true,
	["bread"] = true,
	["chip"] = true,
	["ametista"] = true,
	["esmeralda"] = true,
	["rubi"] = true,
	["safira"] = true,
	["premiumplate"] = true,
	["newgarage"] = true,
	["newchars"] = true,
	["newprops"] = true,
	["namechange"] = true,
	["homecont01"] = true,
	["homecont02"] = true,
	["homecont03"] = true,
	["homecont04"] = true,
	["homecont05"] = true,
	["homecont06"] = true,
	["homecont07"] = true,
	["homecont08"] = true,
	["homecont09"] = true
}

-----------------------------------------------------------------------------------------------------------------------------------------
-- FRUITS
-----------------------------------------------------------------------------------------------------------------------------------------
fruits = {
	["orange"] = true,
	["strawberry"] = true,
	["grape"] = true,
	["banana"] = true,
	["passion"] = true,
	["tange"] = true,
	["tomato"] = true,
	["orangejuice"] = true,
	["tangejuice"] = true,
	["grapejuice"] = true,
	["strawberryjuice"] = true,
	["bananajuice"] = true,
	["passionjuice"] = true,
	["meatA"] = true,
	["meatB"] = true,
	["meatC"] = true,
	["meatS"] = true,
    ["chocolate"] = true
}

-----------------------------------------------------------------------------------------------------------------------------------------
-- NOCOP
-----------------------------------------------------------------------------------------------------------------------------------------
noCop = {
	["WEAPON"] = true,
	["evidence01"] = true,
	["evidence02"] = true,
	["evidence03"] = true,
	["evidence04"] = true,
	["vest"] = true,
	["card01"] = true,
	["card02"] = true,
	["card03"] = true,
	["card04"] = true,
	["card05"] = true,
	["c4"] = true,
	["credential"] = true,
	["adrenaline"] = true,
	["joint"] = true,
	["lean"] = true,
	["ecstasy"] = true,
	["cocaine"] = true,
	["meth"] = true,
	["plate"] = true,
	["lockpick"] = true,
	["lockpick2"] = true,
	["handcuff"] = true,
	["hood"] = true,
	["goldbar"] = true,
	["pager"] = true,
	["oxy"] = true,
	["gsrkit"] = true,
	["gdtkit"] = true,
	["pendrive"] = true,
	["TOKEN_"] = true,
	["dollarsz"] = true
}